package com.aliothmoon.maafw.project

import kotlinx.serialization.json.*
import java.io.File
import java.util.Base64

/** ZIP bytes generated by mah_res/tools/build_release.py, not by the Android implementation. */
internal class ResourceProtocolFixture(private val directory: File) {
    private val fixture = Json.parseToJsonElement(javaClass.getResource("/resource-protocol/producer-fixture.json")!!.readText()).jsonObject
    fun descriptor(version: String): ResourceReleaseDescription = Json.decodeFromJsonElement(fixture.getValue(version).jsonObject.getValue("descriptor"))
    fun description(version: String, kind: String): ResourcePackageDescription = descriptor(version).packages.single { it.manifest.kind == kind }
    fun bytes(version: String, kind: String): ByteArray = Base64.getDecoder().decode(
        fixture.getValue(version).jsonObject.getValue("archives").jsonObject.getValue(description(version, kind).name).jsonPrimitive.content,
    )
    fun archive(version: String, kind: String): ResourceArchive {
        val desc = description(version, kind)
        val file = File(directory, desc.name).also { it.writeBytes(bytes(version, kind)) }
        return ResourceArchive(file, version, desc)
    }
    fun root(): File = File(directory, "pi").also {
        it.mkdirs()
        File(it, "interface.json").writeText("""{"interface_version":2,"name":"test","resource":[{"name":"base","path":["resource/base"]}]}""")
        File(it, "data").mkdirs()
        File(it, "data/custom.json").writeText("user combat")
        File(it, "config").mkdirs()
        File(it, "config/user.json").writeText("user configuration")
        File(it, "resource/base/image").mkdirs()
        File(it, "resource/base/image/own.png").writeText("project UI")
    }
}
